// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace QFramework.PaokuDemo
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:70fff6b0-88b1-4da8-9c10-e716e2d0b69c
    public partial class GameUI
    {
        
        public const string NAME = "GameUI";
        
        [SerializeField()]
        public UnityEngine.UI.Image UIBoard;
        
        [SerializeField()]
        public UnityEngine.UI.Slider Timer;
        
        [SerializeField()]
        public UnityEngine.UI.Text TimerText;
        
        [SerializeField()]
        public UnityEngine.UI.Text coinText;
        
        [SerializeField()]
        public UnityEngine.UI.Text distanceText;
        
        [SerializeField()]
        public UnityEngine.UI.Button PauseButton;
        
        [SerializeField()]
        public UnityEngine.UI.Image UIFinalScore;
        
        [SerializeField()]
        public UnityEngine.UI.Text distanceCount;
        
        [SerializeField()]
        public UnityEngine.UI.Text coinCount;
        
        [SerializeField()]
        public UnityEngine.UI.Text ScoreText;
        
        [SerializeField()]
        public UnityEngine.UI.Button homeBtn;
        
        [SerializeField()]
        public UnityEngine.UI.Button continueBtn;
        
        [SerializeField()]
        public UnityEngine.UI.Image UIDead;
        
        [SerializeField()]
        public UnityEngine.UI.Button UIDeadcancle;
        
        [SerializeField()]
        public UnityEngine.UI.Text UIDeadCoinText;
        
        [SerializeField()]
        public UnityEngine.UI.Button UIDeadbuyButton;
        
        [SerializeField()]
        public UnityEngine.UI.Image UIPause;
        
        [SerializeField()]
        public UnityEngine.UI.Text PauseScore;
        
        [SerializeField()]
        public UnityEngine.UI.Text PauseCoin;
        
        [SerializeField()]
        public UnityEngine.UI.Text PauseDistance;
        
        [SerializeField()]
        public UnityEngine.UI.Button PausecontinueBtn;
        
        [SerializeField()]
        public UnityEngine.UI.Button PausehomeBtn;
        
        [SerializeField()]
        public UnityEngine.UI.Image UIResume;
        
        [SerializeField()]
        public UnityEngine.UI.Image resumeImage;
        
        private GameUIData mPrivateData = null;
        
        public GameUIData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new GameUIData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            UIBoard = null;
            Timer = null;
            TimerText = null;
            coinText = null;
            distanceText = null;
            PauseButton = null;
            UIFinalScore = null;
            distanceCount = null;
            coinCount = null;
            ScoreText = null;
            homeBtn = null;
            continueBtn = null;
            UIDead = null;
            UIDeadcancle = null;
            UIDeadCoinText = null;
            UIDeadbuyButton = null;
            UIPause = null;
            PauseScore = null;
            PauseCoin = null;
            PauseDistance = null;
            PausecontinueBtn = null;
            PausehomeBtn = null;
            UIResume = null;
            resumeImage = null;
            mData = null;
        }
    }
}
